/*ELIMINAR TABLAS TEMPORALES*/

DROP TABLE TEMP_REGION;
DROP TABLE TEMP_ENCUESTA;
DROP TABLE TEMP_DATOS;

/*ELIMINAR TABLAS ER*/


DROP TABLE PAIS_ENCUESTA;
DROP TABLE RESPUESTA;
DROP TABLE PREGUNTA;
DROP TABLE ENCUESTA;
DROP TABLE PROFESIONAL_AREA;
DROP TABLE AREA;
DROP TABLE PROFESIONAL_INVENTO;
DROP TABLE PROFESIONAL;
DROP TABLE INVENTOR_INVENTO;
DROP TABLE INVENTOR;
DROP TABLE INVENTO;
DROP TABLE FRONTERA;
DROP TABLE PAIS;
DROP TABLE REGION;

/*TABLAS TEMPORALES*/

CREATE TABLE TEMP_REGION(
	region VARCHAR(50),
    region_pertenece VARCHAR(50)
);

CREATE TABLE TEMP_ENCUESTA(
	encuesta VARCHAR(50),
    pregunta VARCHAR(250),
    respuesta VARCHAR(50),
    correcta VARCHAR(10),
    pais VARCHAR(50)
);

CREATE TABLE TEMP_DATOS(
	invento VARCHAR(50),
    inventor VARCHAR(50),
    profesional_invento VARCHAR(50),
    jefe_area VARCHAR(30),
    fecha_contraro DATE,
    salario INT,
    comision INT,
    area_investigacion VARCHAR(30),
    ranking INT,
    anio INT,
    pais_invento VARCHAR(50),
    pais_inventor VARCHAR(50),
    region VARCHAR(50),
    capital VARCHAR(50),
    poblacion INT,
    area INT,
    frontera VARCHAR(50),
    norte VARCHAR(10),
    sur VARCHAR(10),
    este VARCHAR(10),
    oeste VARCHAR(10)
);


/* MODELO LOGICO */
CREATE TABLE REGION(
	id_region INT AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(50) NOT NULL,
    id_region1 INT,
    FOREIGN KEY (id_region1) REFERENCES REGION(id_region)
);

CREATE TABLE ENCUESTA(
	id_encuesta INT AUTO_INCREMENT PRIMARY KEY,
    encuesta VARCHAR(50) NOT NULL
);

CREATE TABLE PREGUNTA(
	id_pregunta INT AUTO_INCREMENT PRIMARY KEY,
    pregunta VARCHAR(250) NOT NULL,
    id_encuesta INT,
    FOREIGN KEY (id_encuesta) REFERENCES ENCUESTA(id_encuesta)
);

CREATE TABLE RESPUESTA(
	id_respuesta INT AUTO_INCREMENT PRIMARY KEY,
    respuesta VARCHAR(50) NOT NULL,
    correcta VARCHAR(10),
    pais VARCHAR(50),
    id_pregunta INT,
    FOREIGN KEY (id_pregunta) REFERENCES PREGUNTA(id_pregunta)
);

CREATE TABLE PAIS(
    id_pais INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50),
    capital VARCHAR(50),
    poblacion INT,
    area INT,
    id_region INT,
    FOREIGN KEY (id_region) REFERENCES REGION(id_region)
);

CREATE TABLE FRONTERA(
    norte VARCHAR(10),
    sur VARCHAR(10),
    este VARCHAR(10),
    oeste VARCHAR(10),
    id_pais INT,
    id_paisF INT,
    FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais),
    FOREIGN KEY (id_paisF) REFERENCES PAIS(id_pais)
);

CREATE TABLE PAIS_ENCUESTA(
    id_pais INT,
    id_respuesta INT,
    FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais),
    FOREIGN KEY (id_respuesta) REFERENCES RESPUESTA(id_respuesta)
);

CREATE TABLE INVENTO(
    id_invento INT AUTO_INCREMENT PRIMARY KEY,
    invento VARCHAR(50),
    anio INT,
    id_pais INT,
    FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais)
);

CREATE TABLE INVENTOR(
    id_inventor INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50),
    id_pais INT,
    FOREIGN KEY (id_pais) REFERENCES PAIS(id_pais)
);

CREATE TABLE INVENTOR_INVENTO(
    id_invento INT,
    id_inventor INT,
    FOREIGN KEY (id_invento) REFERENCES INVENTO(id_invento),
    FOREIGN KEY (id_inventor) REFERENCES INVENTOR(id_inventor)
);

CREATE TABLE PROFESIONAL(
    id_profesional INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50),
    fecha_contratacion DATE,
    salario INT,
    comision INT,
    jefe VARCHAR(30)
);

CREATE TABLE AREA(
    id_area INT AUTO_INCREMENT PRIMARY KEY,
    area_investigacion VARCHAR(50),
    ranking INT
);

CREATE TABLE PROFESIONAL_INVENTO(
    id_invento INT,
    id_profesional INT,
    FOREIGN KEY (id_invento) REFERENCES INVENTO(id_invento),
    FOREIGN KEY (id_profesional) REFERENCES PROFESIONAL(id_profesional)
);

CREATE TABLE PROFESIONAL_AREA(
    id_area INT,
    id_profesional INT,
    FOREIGN KEY (id_area) REFERENCES AREA(id_area),
    FOREIGN KEY (id_profesional) REFERENCES PROFESIONAL(id_profesional)
);

/*CARGA MASIVA*/

LOAD DATA INFILE '[CI]Regiones_V2.csv'
IGNORE INTO TABLE TEMP_REGION
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/*ESTA ES*/
LOAD DATA INFILE '[CI]Encuestas.csv'
IGNORE INTO TABLE TEMP_ENCUESTA
COLUMNS TERMINATED BY ';'
LINES TERMINATED BY '\r'
IGNORE 1 LINES;


LOAD DATA INFILE '[CI]Datos.csv'
IGNORE INTO TABLE TEMP_DATOS
COLUMNS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 2 LINES
(	invento,
    inventor,
    profesional_invento,
    jefe_area,
    @fecha_contraro,
    salario,
    comision,
    area_investigacion,
    ranking,
    anio,
    pais_invento,
    pais_inventor,
    region,
    capital,
    poblacion,
    area,
    frontera,
    norte,
    sur,
    este,
    oeste)
SET fecha_contraro = STR_TO_DATE(@fecha_contraro, '%d-%b-%y');


/*LLENADO DEL ER DESDE TABLAS TEMPORALES*/
INSERT INTO REGION(
    REGION.region,
    REGION.id_region1
)
SELECT DISTINCT 
    TEMP_REGION.region,
    IF(STRCMP(REGION.id_region,'') = 0,NULL,REGION.id_region)
FROM TEMP_REGION 
LEFT JOIN REGION
ON TEMP_REGION.region_pertenece = REGION.region;
CALL TEMP_REGION_region_pertenece();


INSERT INTO ENCUESTA(
    ENCUESTA.encuesta
)
SELECT DISTINCT 
    TEMP_ENCUESTA.encuesta
FROM TEMP_ENCUESTA;

INSERT INTO PREGUNTA(
    PREGUNTA.pregunta,
    PREGUNTA.id_encuesta
)
SELECT DISTINCT 
    TEMP_ENCUESTA.pregunta,
    ENCUESTA.id_encuesta    
FROM TEMP_ENCUESTA
INNER JOIN ENCUESTA
ON ENCUESTA.encuesta = TEMP_ENCUESTA.encuesta;

INSERT INTO RESPUESTA(
    RESPUESTA.respuesta,
    RESPUESTA.correcta,
    RESPUESTA.pais,
    RESPUESTA.id_pregunta
)
SELECT  
    TEMP_ENCUESTA.respuesta,
    TEMP_ENCUESTA.correcta,
    TEMP_ENCUESTA.pais,
    PREGUNTA.id_pregunta    
FROM TEMP_ENCUESTA
INNER JOIN PREGUNTA
ON PREGUNTA.pregunta = TEMP_ENCUESTA.pregunta;

INSERT INTO PAIS(
    PAIS.nombre,
    PAIS.capital,
    PAIS.poblacion,
    PAIS.area,
    PAIS.id_region
)
SELECT DISTINCT 
    TEMP_DATOS.pais_inventor,
    TEMP_DATOS.capital,
    TEMP_DATOS.poblacion,
    TEMP_DATOS.area,
    REGION.id_region
FROM TEMP_DATOS
INNER JOIN REGION
ON REGION.region = TEMP_DATOS.region;
CALL REGION_region_TEMP_DATOS_region();

INSERT INTO FRONTERA(
    FRONTERA.norte,
    FRONTERA.sur,
    FRONTERA.este,
    FRONTERA.oeste,
    FRONTERA.id_pais,
    FRONTERA.id_paisF
)
SELECT DISTINCT
    TEMP_DATOS.norte,
    TEMP_DATOS.sur,
    TEMP_DATOS.este,
    TEMP_DATOS.oeste,
    PAISS.id_pais,
    FRONTERA.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS PAISS
ON PAISS.nombre = TEMP_DATOS.pais_inventor
INNER JOIN PAIS FRONTERA
ON FRONTERA.nombre = TEMP_DATOS.frontera;

INSERT INTO PAIS_ENCUESTA(
    PAIS_ENCUESTA.id_pais,
    PAIS_ENCUESTA.id_respuesta
)
SELECT PAIS.id_pais,SUB1.IDR FROM (
SELECT DISTINCT RESPUESTA.id_respuesta IDR,RESPUESTA.respuesta,RESPUESTA.correcta,RESPUESTA.pais AS PAISR FROM
	RESPUESTA 
	INNER JOIN TEMP_ENCUESTA
	ON RESPUESTA.pais = TEMP_ENCUESTA.pais
)SUB1 INNER JOIN
PAIS ON PAIS.nombre = SUB1.PAISR;
CALL PAIS_nombre_SUB1_PAISR();

INSERT INTO INVENTO(
    INVENTO.invento,
    INVENTO.anio,
    INVENTO.id_pais
)
SELECT DISTINCT 
    TEMP_DATOS.invento,
    TEMP_DATOS.anio,
    PAIS.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS 
ON TEMP_DATOS.pais_invento = PAIS.nombre;

INSERT INTO INVENTOR(
    INVENTOR.nombre,
    INVENTOR.id_pais
)
SELECT DISTINCT 
    TEMP_DATOS.inventor,
    PAIS.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS 
ON TEMP_DATOS.pais_inventor = PAIS.nombre
WHERE TEMP_DATOS.inventor != '';

INSERT INTO INVENTOR_INVENTO(
    INVENTOR_INVENTO.id_invento,
    INVENTOR_INVENTO.id_inventor
)SELECT DISTINCT INVENTO.id_invento,INVENTOR.id_inventor FROM(
	SELECT DISTINCT TEMP_DATOS.INVENTO INVENTO_S,TEMP_DATOS.INVENTOR INVENTOR_S
	FROM TEMP_DATOS
)SUB1
INNER JOIN INVENTOR
ON INVENTOR.nombre = SUB1.INVENTOR_S
INNER JOIN INVENTO
ON INVENTO.invento = SUB1.INVENTO_S;


INSERT INTO PROFESIONAL(
	PROFESIONAL.nombre,
    PROFESIONAL.fecha_contratacion,
    PROFESIONAL.salario,
    PROFESIONAL.comision
)
SELECT DISTINCT 
    TEMP_DATOS.profesional_invento,
    TEMP_DATOS.fecha_contraro,
    TEMP_DATOS.salario,
    TEMP_DATOS.comision
FROM TEMP_DATOS
WHERE TEMP_DATOS.profesional_invento != '';

INSERT INTO AREA(
	AREA.area_investigacion,
    AREA.ranking
)
SELECT DISTINCT 
    TEMP_DATOS.area_investigacion,
    TEMP_DATOS.ranking
FROM TEMP_DATOS
WHERE TEMP_DATOS.area_investigacion != '';

INSERT INTO PROFESIONAL_INVENTO(
    PROFESIONAL_INVENTO.id_invento,
    PROFESIONAL_INVENTO.id_profesional
)SELECT DISTINCT INVENTO.id_invento,PROFESIONAL.id_profesional FROM(
	SELECT DISTINCT TEMP_DATOS.INVENTO INVENTO_S,TEMP_DATOS.profesional_invento PROFESIONAL_S
	FROM TEMP_DATOS
)SUB1
INNER JOIN PROFESIONAL
ON PROFESIONAL.nombre = SUB1.PROFESIONAL_S
INNER JOIN INVENTO
ON INVENTO.invento = SUB1.INVENTO_S
WHERE SUB1.INVENTO_S != '';


INSERT INTO PROFESIONAL_AREA(
    PROFESIONAL_AREA.id_area,
    PROFESIONAL_AREA.id_profesional
)SELECT DISTINCT AREA.id_area,PROFESIONAL.id_profesional FROM(
	SELECT DISTINCT TEMP_DATOS.area_investigacion AREA_S,TEMP_DATOS.profesional_invento PROFESIONAL_S
	FROM TEMP_DATOS
    WHERE TEMP_DATOS.area_investigacion != ''
)SUB1
INNER JOIN PROFESIONAL
ON PROFESIONAL.nombre = SUB1.PROFESIONAL_S
INNER JOIN AREA
ON AREA.area_investigacion = SUB1.AREA_S
WHERE SUB1.AREA_S != '';



/*COUNTS*/
SELECT COUNT(*) AS PAIS_ENCUESTA FROM PAIS_ENCUESTA;
SELECT COUNT(*) AS RESPUESTA FROM RESPUESTA;
SELECT COUNT(*) AS PREGUNTA FROM PREGUNTA;
SELECT COUNT(*) AS ENCUESTA FROM ENCUESTA;
SELECT COUNT(*) AS PROFESIONAL_AREA FROM PROFESIONAL_AREA;
SELECT COUNT(*) AS AREA FROM AREA;
SELECT COUNT(*) AS PROFESIONAL_INVENTO FROM PROFESIONAL_INVENTO;
SELECT COUNT(*) AS PROFESIONAL FROM PROFESIONAL;
SELECT COUNT(*) AS INVENTOR_INVENTO FROM INVENTOR_INVENTO;
SELECT COUNT(*) AS INVENTOR FROM INVENTOR;
SELECT COUNT(*) AS INVENTO FROM INVENTO;
SELECT COUNT(*) AS FRONTERA FROM FRONTERA;
SELECT COUNT(*) AS PAIS FROM PAIS;
SELECT COUNT(*) AS REGION FROM REGION;

/*CONSULTAS*/
/*CONSULTA 1*/
SELECT ENCUESTA.encuesta, COUNT(PAIS.nombre) FROM ENCUESTA
INNER JOIN PREGUNTA ON ENCUESTA.id_encuesta = PREGUNTA.id_encuesta
INNER JOIN RESPUESTA ON PREGUNTA.id_pregunta = RESPUESTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS.id_pais = PAIS_ENCUESTA.id_pais
GROUP BY ENCUESTA.encuesta 
ORDER BY 2 DESC;

/*CONSULTA 2*/
SELECT DISTINCT PAIS.nombre FROM PAIS
LEFT JOIN INVENTOR ON PAIS.id_pais = INVENTOR.id_pais
LEFT JOIN FRONTERA ON PAIS.id_pais = FRONTERA.id_pais
WHERE INVENTOR.id_pais IS NULL AND FRONTERA.id_paisF IS NOT NULL;

/*CONSULTA 3*/
SELECT PROFESIONAL.nombre,PROFESIONAL.salario,PROFESIONAL.comision,SUM(salario-comision) MAYOR FROM PROFESIONAL
GROUP BY PROFESIONAL.nombre,PROFESIONAL.salario,PROFESIONAL.comision;

/*CONSULTA 4*/
SELECT PAIS.nombre, PAIS.poblacion FROM PAIS
LEFT JOIN FRONTERA ON PAIS.id_pais = FRONTERA.id_pais
WHERE FRONTERA.id_paisF IS NULL AND PAIS.area > (SELECT PAIS.area FROM PAIS WHERE PAIS.nombre = 'Japon');

/*CONSULTA 5*/
WITH Q1 AS(
	SELECT DISTINCT AREA.area_investigacion AREA_Q1 FROM INVENTO
	INNER JOIN PROFESIONAL_INVENTO ON INVENTO.id_invento = PROFESIONAL_INVENTO.id_invento
	INNER JOIN PROFESIONAL ON PROFESIONAL.id_profesional = PROFESIONAL_INVENTO.id_profesional
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON AREA.id_area = PROFESIONAL_AREA.id_area
	WHERE PROFESIONAL.nombre = 'JAMES CLERK'
)SELECT DISTINCT INVENTO.invento FROM INVENTO
	INNER JOIN PROFESIONAL_INVENTO ON INVENTO.id_invento = PROFESIONAL_INVENTO.id_invento
	INNER JOIN PROFESIONAL ON PROFESIONAL.id_profesional = PROFESIONAL_INVENTO.id_profesional
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON AREA.id_area = PROFESIONAL_AREA.id_area
	WHERE AREA.area_investigacion = (SELECT Q1.AREA_Q1 FROM Q1);

/*CONSULTA 6*/
SELECT SUB1.NOMBRE_PAIS,SUB1.NUMERO_INVENTOS FROM (SELECT PAIS.nombre NOMBRE_PAIS,COUNT(INVENTO.invento) NUMERO_INVENTOS  FROM INVENTO
INNER JOIN PAIS ON INVENTO.id_pais = PAIS.id_pais
GROUP BY PAIS.nombre)SUB1
WHERE SUB1.NUMERO_INVENTOS > 3
ORDER BY 2 DESC;

/*CONSULTA 7*/
SELECT PAIS.nombre FROM PAIS
WHERE PAIS.area > (SELECT SUM(PAIS.area) FROM REGION
INNER JOIN PAIS ON REGION.id_region = PAIS.id_region
WHERE REGION.region = 'Centro America');

/*CONSULTA 8*/
SELECT PROFESIONAL.nombre, COUNT(INVENTO.invento) FROM PROFESIONAL
INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional = PROFESIONAL.id_profesional
INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
GROUP BY PROFESIONAL.nombre 
ORDER BY 2 DESC;

/*CONSULTA 9*/
WITH Q1 AS(
	SELECT AREA.area_investigacion,SUM(PROFESIONAL.salario) SUMA_OPTICA FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	WHERE AREA.area_investigacion = 'Óptica'
	GROUP BY AREA.area_investigacion
)SELECT SUB1.AREAS,SUB1.SUM_AREA FROM (
	SELECT AREA.area_investigacion AREAS,SUM(PROFESIONAL.salario) SUM_AREA FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	GROUP BY AREA.area_investigacion
)SUB1 
WHERE SUB1.SUM_AREA > (SELECT Q1.SUMA_OPTICA FROM Q1)
ORDER BY 2 DESC;

/*CONSULTA 10*/
WITH Q1 AS(
	SELECT INVENTO.anio ANIO_INVENTO FROM INVENTO 
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
	WHERE INVENTOR.nombre = 'Benz'
)SELECT SUB1.INVENTOS FROM (
	SELECT INVENTO.invento INVENTOS, INVENTO.anio ANIOS  FROM INVENTO 
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
)SUB1 
WHERE SUB1.ANIOS = (SELECT Q1.ANIO_INVENTO FROM Q1);

/*CONSULTA 11*/
SELECT INVENTOR.nombre, INVENTO.invento FROM INVENTO 
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE INVENTO.invento LIKE "%Maquina%";


/*CONSULTA 12*/
SELECT DISTINCT * FROM(
	SELECT PAIS.nombre, COUNT(RESPUESTA.respuesta) FROM ENCUESTA
INNER JOIN PREGUNTA ON PREGUNTA.id_encuesta = ENCUESTA.id_encuesta
INNER JOIN RESPUESTA ON RESPUESTA.id_pregunta = PREGUNTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS_ENCUESTA.id_pais = PAIS.id_pais
WHERE RESPUESTA.correcta = 'SI'
GROUP BY PAIS.nombre
UNION
SELECT PAIS.nombre, NULL FROM ENCUESTA
INNER JOIN PREGUNTA ON PREGUNTA.id_encuesta = ENCUESTA.id_encuesta
INNER JOIN RESPUESTA ON RESPUESTA.id_pregunta = PREGUNTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS_ENCUESTA.id_pais = PAIS.id_pais
WHERE RESPUESTA.correcta = 'NO'
GROUP BY PAIS.nombre
)SUB1;


/*CONSULTA 13*/
SELECT INVENTOR.nombre, INVENTO.invento INVENTOS, INVENTO.anio ANIOS  FROM INVENTO 
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE INVENTO.anio < 1800 OR INVENTO.anio > 1900;

/*CONSULTA 14*/
SELECT PAIS.nombre, COUNT(INVENTO.invento) FROM PAIS
INNER JOIN INVENTO ON INVENTO.id_pais = PAIS.id_pais
GROUP BY PAIS.nombre
ORDER BY 1;

/*CONSULTA 15*/
SELECT AREA.area_investigacion,MAX(PROFESIONAL.salario),MIN(PROFESIONAL.salario) FROM PROFESIONAL
INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
WHERE PROFESIONAL.salario > 1000
GROUP BY AREA.area_investigacion;

/*CONSULTA 16*/
WITH Q1 AS(
	SELECT DISTINCT INVENTOR.nombre NOMBRE_INVENTOR_Q1,PROFESIONAL.nombre, AREA.area_investigacion FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
	INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
	WHERE INVENTOR.nombre = 'Pasteur'
),Q2 AS (
	SELECT DISTINCT PROFESIONAL.nombre NOMBRE_INVENTOR, PROFESIONAL.jefe,AREA.area_investigacion FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
	INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
    WHERE AREA.area_investigacion != 'Biología'
)
SELECT DISTINCT PROFESIONAL.nombre NOMBRE_INVENTOR, PROFESIONAL.jefe FROM PROFESIONAL
INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE AREA.area_investigacion != 'Biología' AND PROFESIONAL.jefe IS NOT NULL;

/*CONSULTA 17*/
SELECT PAIS.nombre FROM PAIS
WHERE PAIS.poblacion > (SELECT SUM(PAIS.poblacion) FROM REGION
INNER JOIN PAIS ON REGION.id_region = PAIS.id_region
WHERE REGION.region = 'Sur America');

/*CONSULTA 18*/
SELECT PADRE.region PADRE, HIJO.region HIJO FROM REGION HIJO
INNER JOIN REGION PADRE ON PADRE.id_region = HIJO.id_region1
UNION
SELECT PADRE.region PADRE, HIJO.nombre HIJO FROM PAIS HIJO
INNER JOIN REGION PADRE ON PADRE.id_region = HIJO.id_region;

/*CONSULTA 19*/
SELECT PAIS_1.nombre, PAIS_2.nombre FROM PAIS PAIS_1
INNER JOIN FRONTERA FRONTERA1 ON PAIS_1.id_pais = FRONTERA1.id_pais
INNER JOIN PAIS PAIS_2 ON PAIS_2.id_pais = FRONTERA1.id_paisF;

/*CONSULTA 20*/
WITH Q1 AS(
	SELECT PAIS_1.nombre PAIS_Q1, REGION.region REGION_Q1,PAIS_1.area AREA_Q1,COUNT(PAIS_2.nombre) Q1_COUNT FROM PAIS PAIS_1
	INNER JOIN FRONTERA FRONTERA1 ON PAIS_1.id_pais = FRONTERA1.id_pais
	INNER JOIN PAIS PAIS_2 ON PAIS_2.id_pais = FRONTERA1.id_paisF
	INNER JOIN REGION ON REGION.id_region = PAIS_1.id_region
	GROUP BY PAIS_1.nombre
)SELECT PAIS_Q1, REGION_Q1,Q1_COUNT FROM Q1 WHERE Q1.Q1_COUNT > 7
ORDER BY AREA_Q1 DESC;