INSERT INTO REGION(
    REGION.region,
    REGION.id_region1
)
SELECT DISTINCT 
    TEMP_REGION.region,
    IF(STRCMP(REGION.id_region,'') = 0,NULL,REGION.id_region)
FROM TEMP_REGION 
LEFT JOIN REGION
ON TEMP_REGION.region_pertenece = REGION.region;
CALL TEMP_REGION_region_pertenece();


INSERT INTO ENCUESTA(
    ENCUESTA.encuesta
)
SELECT DISTINCT 
    TEMP_ENCUESTA.encuesta
FROM TEMP_ENCUESTA;

INSERT INTO PREGUNTA(
    PREGUNTA.pregunta,
    PREGUNTA.id_encuesta
)
SELECT DISTINCT 
    TEMP_ENCUESTA.pregunta,
    ENCUESTA.id_encuesta    
FROM TEMP_ENCUESTA
INNER JOIN ENCUESTA
ON ENCUESTA.encuesta = TEMP_ENCUESTA.encuesta;

INSERT INTO RESPUESTA(
    RESPUESTA.respuesta,
    RESPUESTA.correcta,
    RESPUESTA.pais,
    RESPUESTA.id_pregunta
)
SELECT  
    TEMP_ENCUESTA.respuesta,
    TEMP_ENCUESTA.correcta,
    TEMP_ENCUESTA.pais,
    PREGUNTA.id_pregunta    
FROM TEMP_ENCUESTA
INNER JOIN PREGUNTA
ON PREGUNTA.pregunta = TEMP_ENCUESTA.pregunta;

INSERT INTO PAIS(
    PAIS.nombre,
    PAIS.capital,
    PAIS.poblacion,
    PAIS.area,
    PAIS.id_region
)
SELECT DISTINCT 
    TEMP_DATOS.pais_inventor,
    TEMP_DATOS.capital,
    TEMP_DATOS.poblacion,
    TEMP_DATOS.area,
    REGION.id_region
FROM TEMP_DATOS
INNER JOIN REGION
ON REGION.region = TEMP_DATOS.region;
CALL REGION_region_TEMP_DATOS_region();

INSERT INTO FRONTERA(
    FRONTERA.norte,
    FRONTERA.sur,
    FRONTERA.este,
    FRONTERA.oeste,
    FRONTERA.id_pais,
    FRONTERA.id_paisF
)
SELECT DISTINCT
    TEMP_DATOS.norte,
    TEMP_DATOS.sur,
    TEMP_DATOS.este,
    TEMP_DATOS.oeste,
    PAISS.id_pais,
    FRONTERA.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS PAISS
ON PAISS.nombre = TEMP_DATOS.pais_inventor
INNER JOIN PAIS FRONTERA
ON FRONTERA.nombre = TEMP_DATOS.frontera;

INSERT INTO PAIS_ENCUESTA(
    PAIS_ENCUESTA.id_pais,
    PAIS_ENCUESTA.id_respuesta
)
SELECT PAIS.id_pais,SUB1.IDR FROM (
SELECT DISTINCT RESPUESTA.id_respuesta IDR,RESPUESTA.respuesta,RESPUESTA.correcta,RESPUESTA.pais AS PAISR FROM
	RESPUESTA 
	INNER JOIN TEMP_ENCUESTA
	ON RESPUESTA.pais = TEMP_ENCUESTA.pais
)SUB1 INNER JOIN
PAIS ON PAIS.nombre = SUB1.PAISR;
CALL PAIS_nombre_SUB1_PAISR();

INSERT INTO INVENTO(
    INVENTO.invento,
    INVENTO.anio,
    INVENTO.id_pais
)
SELECT DISTINCT 
    TEMP_DATOS.invento,
    TEMP_DATOS.anio,
    PAIS.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS 
ON TEMP_DATOS.pais_invento = PAIS.nombre;

INSERT INTO INVENTOR(
    INVENTOR.nombre,
    INVENTOR.id_pais
)
SELECT DISTINCT 
    TEMP_DATOS.inventor,
    PAIS.id_pais
FROM TEMP_DATOS
INNER JOIN PAIS 
ON TEMP_DATOS.pais_inventor = PAIS.nombre
WHERE TEMP_DATOS.inventor != '';

INSERT INTO INVENTOR_INVENTO(
    INVENTOR_INVENTO.id_invento,
    INVENTOR_INVENTO.id_inventor
)SELECT DISTINCT INVENTO.id_invento,INVENTOR.id_inventor FROM(
	SELECT DISTINCT TEMP_DATOS.INVENTO INVENTO_S,TEMP_DATOS.INVENTOR INVENTOR_S
	FROM TEMP_DATOS
)SUB1
INNER JOIN INVENTOR
ON INVENTOR.nombre = SUB1.INVENTOR_S
INNER JOIN INVENTO
ON INVENTO.invento = SUB1.INVENTO_S;


INSERT INTO PROFESIONAL(
	PROFESIONAL.nombre,
    PROFESIONAL.fecha_contratacion,
    PROFESIONAL.salario,
    PROFESIONAL.comision
)
SELECT DISTINCT 
    TEMP_DATOS.profesional_invento,
    TEMP_DATOS.fecha_contraro,
    TEMP_DATOS.salario,
    TEMP_DATOS.comision
FROM TEMP_DATOS
WHERE TEMP_DATOS.profesional_invento != '';

INSERT INTO AREA(
	AREA.area_investigacion,
    AREA.ranking
)
SELECT DISTINCT 
    TEMP_DATOS.area_investigacion,
    TEMP_DATOS.ranking
FROM TEMP_DATOS
WHERE TEMP_DATOS.area_investigacion != '';

INSERT INTO PROFESIONAL_INVENTO(
    PROFESIONAL_INVENTO.id_invento,
    PROFESIONAL_INVENTO.id_profesional
)SELECT DISTINCT INVENTO.id_invento,PROFESIONAL.id_profesional FROM(
	SELECT DISTINCT TEMP_DATOS.INVENTO INVENTO_S,TEMP_DATOS.profesional_invento PROFESIONAL_S
	FROM TEMP_DATOS
)SUB1
INNER JOIN PROFESIONAL
ON PROFESIONAL.nombre = SUB1.PROFESIONAL_S
INNER JOIN INVENTO
ON INVENTO.invento = SUB1.INVENTO_S
WHERE SUB1.INVENTO_S != '';


INSERT INTO PROFESIONAL_AREA(
    PROFESIONAL_AREA.id_area,
    PROFESIONAL_AREA.id_profesional
)SELECT DISTINCT AREA.id_area,PROFESIONAL.id_profesional FROM(
	SELECT DISTINCT TEMP_DATOS.area_investigacion AREA_S,TEMP_DATOS.profesional_invento PROFESIONAL_S
	FROM TEMP_DATOS
    WHERE TEMP_DATOS.area_investigacion != ''
)SUB1
INNER JOIN PROFESIONAL
ON PROFESIONAL.nombre = SUB1.PROFESIONAL_S
INNER JOIN AREA
ON AREA.area_investigacion = SUB1.AREA_S
WHERE SUB1.AREA_S != '';