/*CONSULTA 1*/
SELECT ENCUESTA.encuesta, COUNT(PAIS.nombre) FROM ENCUESTA
INNER JOIN PREGUNTA ON ENCUESTA.id_encuesta = PREGUNTA.id_encuesta
INNER JOIN RESPUESTA ON PREGUNTA.id_pregunta = RESPUESTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS.id_pais = PAIS_ENCUESTA.id_pais
GROUP BY ENCUESTA.encuesta 
ORDER BY 2 DESC;

/*CONSULTA 2*/
SELECT DISTINCT PAIS.nombre FROM PAIS
LEFT JOIN INVENTOR ON PAIS.id_pais = INVENTOR.id_pais
LEFT JOIN FRONTERA ON PAIS.id_pais = FRONTERA.id_pais
WHERE INVENTOR.id_pais IS NULL AND FRONTERA.id_paisF IS NOT NULL;

/*CONSULTA 3*/
SELECT PROFESIONAL.nombre,PROFESIONAL.salario,PROFESIONAL.comision,SUM(salario-comision) MAYOR FROM PROFESIONAL
GROUP BY PROFESIONAL.nombre,PROFESIONAL.salario,PROFESIONAL.comision;

/*CONSULTA 4*/
SELECT PAIS.nombre, PAIS.poblacion FROM PAIS
LEFT JOIN FRONTERA ON PAIS.id_pais = FRONTERA.id_pais
WHERE FRONTERA.id_paisF IS NULL AND PAIS.area > (SELECT PAIS.area FROM PAIS WHERE PAIS.nombre = 'Japon');

/*CONSULTA 5*/
WITH Q1 AS(
	SELECT DISTINCT AREA.area_investigacion AREA_Q1 FROM INVENTO
	INNER JOIN PROFESIONAL_INVENTO ON INVENTO.id_invento = PROFESIONAL_INVENTO.id_invento
	INNER JOIN PROFESIONAL ON PROFESIONAL.id_profesional = PROFESIONAL_INVENTO.id_profesional
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON AREA.id_area = PROFESIONAL_AREA.id_area
	WHERE PROFESIONAL.nombre = 'JAMES CLERK'
)SELECT DISTINCT INVENTO.invento FROM INVENTO
	INNER JOIN PROFESIONAL_INVENTO ON INVENTO.id_invento = PROFESIONAL_INVENTO.id_invento
	INNER JOIN PROFESIONAL ON PROFESIONAL.id_profesional = PROFESIONAL_INVENTO.id_profesional
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON AREA.id_area = PROFESIONAL_AREA.id_area
	WHERE AREA.area_investigacion = (SELECT Q1.AREA_Q1 FROM Q1);

/*CONSULTA 6*/
SELECT SUB1.NOMBRE_PAIS,SUB1.NUMERO_INVENTOS FROM (SELECT PAIS.nombre NOMBRE_PAIS,COUNT(INVENTO.invento) NUMERO_INVENTOS  FROM INVENTO
INNER JOIN PAIS ON INVENTO.id_pais = PAIS.id_pais
GROUP BY PAIS.nombre)SUB1
WHERE SUB1.NUMERO_INVENTOS > 3
ORDER BY 2 DESC;

/*CONSULTA 7*/
SELECT PAIS.nombre FROM PAIS
WHERE PAIS.area > (SELECT SUM(PAIS.area) FROM REGION
INNER JOIN PAIS ON REGION.id_region = PAIS.id_region
WHERE REGION.region = 'Centro America');

/*CONSULTA 8*/
SELECT PROFESIONAL.nombre, COUNT(INVENTO.invento) FROM PROFESIONAL
INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional = PROFESIONAL.id_profesional
INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
GROUP BY PROFESIONAL.nombre 
ORDER BY 2 DESC;

/*CONSULTA 9*/
WITH Q1 AS(
	SELECT AREA.area_investigacion,SUM(PROFESIONAL.salario) SUMA_OPTICA FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	WHERE AREA.area_investigacion = 'Óptica'
	GROUP BY AREA.area_investigacion
)SELECT SUB1.AREAS,SUB1.SUM_AREA FROM (
	SELECT AREA.area_investigacion AREAS,SUM(PROFESIONAL.salario) SUM_AREA FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	GROUP BY AREA.area_investigacion
)SUB1 
WHERE SUB1.SUM_AREA > (SELECT Q1.SUMA_OPTICA FROM Q1)
ORDER BY 2 DESC;

/*CONSULTA 10*/
WITH Q1 AS(
	SELECT INVENTO.anio ANIO_INVENTO FROM INVENTO 
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
	WHERE INVENTOR.nombre = 'Benz'
)SELECT SUB1.INVENTOS FROM (
	SELECT INVENTO.invento INVENTOS, INVENTO.anio ANIOS  FROM INVENTO 
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
)SUB1 
WHERE SUB1.ANIOS = (SELECT Q1.ANIO_INVENTO FROM Q1);

/*CONSULTA 11*/
SELECT INVENTOR.nombre, INVENTO.invento FROM INVENTO 
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE INVENTO.invento LIKE "%Maquina%";


/*CONSULTA 12*/
SELECT DISTINCT * FROM(
	SELECT PAIS.nombre, COUNT(RESPUESTA.respuesta) FROM ENCUESTA
INNER JOIN PREGUNTA ON PREGUNTA.id_encuesta = ENCUESTA.id_encuesta
INNER JOIN RESPUESTA ON RESPUESTA.id_pregunta = PREGUNTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS_ENCUESTA.id_pais = PAIS.id_pais
WHERE RESPUESTA.correcta = 'SI'
GROUP BY PAIS.nombre
UNION
SELECT PAIS.nombre, NULL FROM ENCUESTA
INNER JOIN PREGUNTA ON PREGUNTA.id_encuesta = ENCUESTA.id_encuesta
INNER JOIN RESPUESTA ON RESPUESTA.id_pregunta = PREGUNTA.id_pregunta
INNER JOIN PAIS_ENCUESTA ON RESPUESTA.id_respuesta = PAIS_ENCUESTA.id_respuesta
INNER JOIN PAIS ON PAIS_ENCUESTA.id_pais = PAIS.id_pais
WHERE RESPUESTA.correcta = 'NO'
GROUP BY PAIS.nombre
)SUB1;


/*CONSULTA 13*/
SELECT INVENTOR.nombre, INVENTO.invento INVENTOS, INVENTO.anio ANIOS  FROM INVENTO 
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE INVENTO.anio < 1800 OR INVENTO.anio > 1900;

/*CONSULTA 14*/
SELECT PAIS.nombre, COUNT(INVENTO.invento) FROM PAIS
INNER JOIN INVENTO ON INVENTO.id_pais = PAIS.id_pais
GROUP BY PAIS.nombre
ORDER BY 1;

/*CONSULTA 15*/
SELECT AREA.area_investigacion,MAX(PROFESIONAL.salario),MIN(PROFESIONAL.salario) FROM PROFESIONAL
INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional = PROFESIONAL.id_profesional
INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
WHERE PROFESIONAL.salario > 1000
GROUP BY AREA.area_investigacion;

/*CONSULTA 16*/
WITH Q1 AS(
	SELECT DISTINCT INVENTOR.nombre NOMBRE_INVENTOR_Q1,PROFESIONAL.nombre, AREA.area_investigacion FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
	INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
	WHERE INVENTOR.nombre = 'Pasteur'
),Q2 AS (
	SELECT DISTINCT PROFESIONAL.nombre NOMBRE_INVENTOR, PROFESIONAL.jefe,AREA.area_investigacion FROM PROFESIONAL
	INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
	INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
	INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
	INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
	INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
    WHERE AREA.area_investigacion != 'Biología'
)
SELECT DISTINCT PROFESIONAL.nombre NOMBRE_INVENTOR, PROFESIONAL.jefe FROM PROFESIONAL
INNER JOIN PROFESIONAL_AREA ON PROFESIONAL_AREA.id_profesional
INNER JOIN AREA ON PROFESIONAL_AREA.id_area = AREA.id_area
INNER JOIN PROFESIONAL_INVENTO ON PROFESIONAL_INVENTO.id_profesional
INNER JOIN INVENTO ON PROFESIONAL_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR_INVENTO ON INVENTOR_INVENTO.id_invento = INVENTO.id_invento
INNER JOIN INVENTOR ON INVENTOR_INVENTO.id_inventor = INVENTOR.id_inventor
WHERE AREA.area_investigacion != 'Biología' AND PROFESIONAL.jefe IS NOT NULL;

/*CONSULTA 17*/
SELECT PAIS.nombre FROM PAIS
WHERE PAIS.poblacion > (SELECT SUM(PAIS.poblacion) FROM REGION
INNER JOIN PAIS ON REGION.id_region = PAIS.id_region
WHERE REGION.region = 'Sur America');

/*CONSULTA 18*/
SELECT PADRE.region PADRE, HIJO.region HIJO FROM REGION HIJO
INNER JOIN REGION PADRE ON PADRE.id_region = HIJO.id_region1
UNION
SELECT PADRE.region PADRE, HIJO.nombre HIJO FROM PAIS HIJO
INNER JOIN REGION PADRE ON PADRE.id_region = HIJO.id_region;

/*CONSULTA 19*/
SELECT PAIS_1.nombre, PAIS_2.nombre FROM PAIS PAIS_1
INNER JOIN FRONTERA FRONTERA1 ON PAIS_1.id_pais = FRONTERA1.id_pais
INNER JOIN PAIS PAIS_2 ON PAIS_2.id_pais = FRONTERA1.id_paisF;

/*CONSULTA 20*/
WITH Q1 AS(
	SELECT PAIS_1.nombre PAIS_Q1, REGION.region REGION_Q1,PAIS_1.area AREA_Q1,COUNT(PAIS_2.nombre) Q1_COUNT FROM PAIS PAIS_1
	INNER JOIN FRONTERA FRONTERA1 ON PAIS_1.id_pais = FRONTERA1.id_pais
	INNER JOIN PAIS PAIS_2 ON PAIS_2.id_pais = FRONTERA1.id_paisF
	INNER JOIN REGION ON REGION.id_region = PAIS_1.id_region
	GROUP BY PAIS_1.nombre
)SELECT PAIS_Q1, REGION_Q1,Q1_COUNT FROM Q1 WHERE Q1.Q1_COUNT > 7
ORDER BY AREA_Q1 DESC;