DROP TABLE REGION;
DROP TABLE PAIS_ENCUESTA;
DROP TABLE RESPUESTA;
DROP TABLE PREGUNTA;
DROP TABLE ENCUESTA;
DROP TABLE PROFESION_AREA;
DROP TABLE AREA;
DROP TABLE PROFESIONAL_INVENTO;
DROP TABLE PROFESIONAL;
DROP TABLE INVENTOR_INVENTO;
DROP TABLE INVENTOR;
DROP TABLE INVENTO;
DROP TABLE FRONTERA;
DROP TABLE PAIS;

